# Generated by Django 4.0.4 on 2022-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_familiares',
            name='fecha_nacimiento',
            field=models.CharField(max_length=100),
        ),
    ]
